#!/usr/bin/env python3
"""
generate_readme.py

Reads data/entries.yml and regenerates README.md. This is the only supported
way to edit the entry list section of README.md - edit entries.yml, then
re-run this script. Everything between the ENTRIES:START and ENTRIES:END
markers is overwritten; everything outside those markers is left alone.

Usage:
    python scripts/generate_readme.py

Requires: PyYAML (see scripts/requirements.txt)
"""
from __future__ import annotations

import pathlib
import sys

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
ENTRIES_FILE = REPO_ROOT / "data" / "entries.yml"
README_FILE = REPO_ROOT / "README.md"

START_MARKER = "<!-- ENTRIES:START - generated by scripts/generate_readme.py, do not hand-edit -->"
END_MARKER = "<!-- ENTRIES:END -->"


def entry_url(entry: dict) -> str:
    if entry.get("url"):
        return entry["url"]
    if entry.get("repo"):
        return f"https://github.com/{entry['repo']}"
    raise ValueError(f"Entry has neither url nor repo: {entry}")


def entry_display_name(entry: dict) -> str:
    if entry.get("name"):
        return entry["name"]
    if entry.get("repo"):
        return entry["repo"].split("/")[-1]
    raise ValueError(f"Entry has no name and no repo to derive one from: {entry}")


def render_entry(entry: dict) -> str:
    name = entry_display_name(entry)
    url = entry_url(entry)
    desc = entry["description"].strip()
    line = f"- **[{name}]({url})** - {desc}"
    if entry.get("maintainer"):
        line += f" _(maintained by {entry['maintainer']})_"
    return line


def render_entries_section(data: dict) -> str:
    categories = data["categories"]
    entries = data["entries"]

    by_category: dict[str, list[dict]] = {c["id"]: [] for c in categories}
    for entry in entries:
        cat_id = entry["category"]
        if cat_id not in by_category:
            raise ValueError(f"Entry {entry.get('name', entry.get('repo'))} has unknown category '{cat_id}'")
        by_category[cat_id].append(entry)

    lines = [START_MARKER, ""]
    for cat in categories:
        cat_entries = by_category[cat["id"]]
        if not cat_entries:
            continue
        lines.append(f"### {cat['title']}")
        lines.append("")
        for entry in cat_entries:
            lines.append(render_entry(entry))
        lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main() -> int:
    if not ENTRIES_FILE.exists():
        print(f"Missing {ENTRIES_FILE}", file=sys.stderr)
        return 1
    if not README_FILE.exists():
        print(f"Missing {README_FILE} - README.md must exist with markers already in place", file=sys.stderr)
        return 1

    data = yaml.safe_load(ENTRIES_FILE.read_text())
    new_section = render_entries_section(data)

    readme_text = README_FILE.read_text()
    if START_MARKER not in readme_text or END_MARKER not in readme_text:
        print("README.md is missing the ENTRIES:START/END markers", file=sys.stderr)
        return 1

    before = readme_text.split(START_MARKER)[0]
    after = readme_text.split(END_MARKER)[1]
    new_readme = before + new_section + after

    README_FILE.write_text(new_readme)
    total = sum(len(v) for v in [data["entries"]])
    print(f"Wrote {README_FILE.relative_to(REPO_ROOT)} - {total} entries across {len(data['categories'])} categories.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
